name: List GCP VMs using Workload Identity

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
permissions:
  id-token: write
  
jobs:
  list-vms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
